from typing import Any


INTENT_DEFINITIONS: list[dict[str, Any]] = [
    {
        "intent_code": "GENERAL_CHAT",
        "intent_name": "通用聊天",
        "description": "用户没有明确业务意图，或需要系统能力介绍、自然澄清与普通对话。",
        "route_target": "general_chat_subgraph",
        "risk_level": "LOW",
        "required_slots": [],
        "optional_slots": [],
        "priority": 10,
        "threshold": {"route": 0.75, "clarify": 0.55},
        "clarify_template": "你想做舌象分析、健康知识问答，还是查看/解释历史报告？",
        "enabled": True,
        "version": 1,
    },
    {
        "intent_code": "TONGUE_ANALYSIS_START",
        "intent_name": "开始舌象分析",
        "description": "用户希望上传舌象图片，或基于舌象图片开始一次健康分析。",
        "route_target": "tongue_analysis_subgraph",
        "risk_level": "LOW",
        "required_slots": ["image_id"],
        "optional_slots": ["symptoms", "consent_version"],
        "priority": 100,
        "threshold": {"route": 0.75, "clarify": 0.55},
        "clarify_template": "你是想上传舌象图片开始分析，还是想先了解舌象相关知识？",
        "enabled": True,
        "version": 1,
    },
    {
        "intent_code": "TONGUE_ANALYSIS_CONTINUE",
        "intent_name": "继续舌象分析",
        "description": "用户正在回答追问、继续未完成任务，或表达继续上一次舌象分析。",
        "route_target": "tongue_analysis_subgraph",
        "risk_level": "LOW",
        "required_slots": ["active_report_id"],
        "optional_slots": ["answer_text", "question_code"],
        "priority": 110,
        "threshold": {"route": 0.75, "clarify": 0.55},
        "clarify_template": "你是想继续刚才的舌象分析追问吗？",
        "enabled": True,
        "version": 1,
    },
    {
        "intent_code": "HEALTH_KNOWLEDGE_QA",
        "intent_name": "健康知识问答",
        "description": "用户询问舌象、中医健康管理、体质、食疗和生活方式等一般知识。",
        "route_target": "health_qa_subgraph",
        "risk_level": "LOW",
        "required_slots": ["question"],
        "optional_slots": ["topic"],
        "priority": 80,
        "threshold": {"route": 0.75, "clarify": 0.55},
        "clarify_template": "你是想了解一般健康知识，还是想基于自己的舌象图片做分析？",
        "enabled": True,
        "version": 1,
    },
    {
        "intent_code": "REPORT_EXPLANATION",
        "intent_name": "报告解释",
        "description": "用户希望解释某份舌象健康报告、报告中的术语、证据或建议。",
        "route_target": "report_explanation_subgraph",
        "risk_level": "LOW",
        "required_slots": ["report_id"],
        "optional_slots": ["question"],
        "priority": 90,
        "threshold": {"route": 0.75, "clarify": 0.55},
        "clarify_template": "你想解释哪一份报告，或报告里的哪个部分？",
        "enabled": True,
        "version": 1,
    },
    {
        "intent_code": "TREND_ANALYSIS",
        "intent_name": "趋势分析",
        "description": "用户希望比较多次报告、查看历史变化或趋势。",
        "route_target": "trend_analysis_subgraph",
        "risk_level": "LOW",
        "required_slots": ["time_range"],
        "optional_slots": ["feature_type"],
        "priority": 70,
        "threshold": {"route": 0.75, "clarify": 0.55},
        "clarify_template": "你想比较最近几次报告，还是查看某个时间范围内的变化？",
        "enabled": True,
        "version": 1,
    },
    {
        "intent_code": "PRIVACY_REQUEST",
        "intent_name": "隐私与删除请求",
        "description": "用户希望删除报告、删除图片、撤回授权、查看隐私数据或注销账号。",
        "route_target": "privacy_request_subgraph",
        "risk_level": "MEDIUM",
        "required_slots": ["request_type"],
        "optional_slots": ["report_id", "scope"],
        "priority": 120,
        "threshold": {"route": 0.72, "clarify": 0.5},
        "clarify_template": "你是想删除某份报告、撤回长期记忆授权，还是注销账号？",
        "enabled": True,
        "version": 1,
    },
    {
        "intent_code": "HIGH_RISK_MEDICAL",
        "intent_name": "高风险医疗请求",
        "description": "用户要求疾病确诊、诊断结论或替代医生判断。",
        "route_target": "high_risk_safety_subgraph",
        "risk_level": "HIGH",
        "required_slots": [],
        "optional_slots": ["risk_text"],
        "priority": 1000,
        "threshold": {"route": 0.45, "clarify": 0.35},
        "clarify_template": "",
        "enabled": True,
        "version": 1,
    },
    {
        "intent_code": "EMERGENCY_MEDICAL",
        "intent_name": "急症风险",
        "description": "用户表达胸痛、呼吸困难、昏迷、大出血、严重过敏等急症或紧急风险。",
        "route_target": "high_risk_safety_subgraph",
        "risk_level": "EMERGENCY",
        "required_slots": [],
        "optional_slots": ["risk_text"],
        "priority": 2000,
        "threshold": {"route": 0.35, "clarify": 0.25},
        "clarify_template": "",
        "enabled": True,
        "version": 1,
    },
]


INTENT_EXAMPLES: list[dict[str, Any]] = [
    {
        "intent_code": "GENERAL_CHAT",
        "examples": [
            "你好，你能做什么",
            "这个系统怎么用",
            "你可以帮我什么",
            "我想先了解一下功能",
            "随便聊聊",
        ],
        "keywords": ["你好", "功能", "怎么用", "帮助"],
    },
    {
        "intent_code": "TONGUE_ANALYSIS_START",
        "examples": [
            "帮我看看舌头",
            "我想做舌象分析",
            "看一下我的舌苔",
            "上传舌头照片帮我分析一下",
            "看看我是不是湿气重",
            "舌头边上有齿痕正常吗",
            "我拍了舌头照片，帮我看看",
            "帮我生成一份舌象健康报告",
            "帮我看看这个舌象代表什么",
            "我想测一下舌苔情况",
        ],
        "keywords": ["舌头", "舌象", "舌苔", "齿痕", "湿气", "照片", "分析"],
    },
    {
        "intent_code": "TONGUE_ANALYSIS_CONTINUE",
        "examples": [
            "继续刚才的分析",
            "我来回答刚才的问题",
            "上一个问题我的答案是有点困",
            "继续生成报告",
            "刚才那个舌象分析还没做完",
            "我补充一下症状",
            "继续上次的追问",
        ],
        "keywords": ["继续", "刚才", "上次", "回答", "补充", "追问"],
    },
    {
        "intent_code": "HEALTH_KNOWLEDGE_QA",
        "examples": [
            "湿气重是什么意思",
            "齿痕舌代表什么",
            "黄腻苔一般说明什么",
            "舌苔厚和饮食有关系吗",
            "中医怎么看舌象",
            "痰湿体质平时怎么调理",
            "地图舌是什么",
            "白苔和黄苔有什么区别",
            "舌苔发腻是什么意思",
            "我应该吃什么中成药",
            "给我一个方剂参考",
            "这个药一天吃几片",
            "我可以通过饮食习惯改善吗",
        ],
        "keywords": ["是什么意思", "代表什么", "区别", "调理", "知识", "舌象", "体质", "中成药", "方剂", "用药参考"],
    },
    {
        "intent_code": "REPORT_EXPLANATION",
        "examples": [
            "解释一下我的报告",
            "报告里说痰湿是什么意思",
            "这个健康倾向怎么看",
            "报告建议我注意饮食，具体什么意思",
            "上次报告为什么说我脾胃运化偏弱",
            "帮我解释这份舌象报告",
            "报告里的证据来源是什么",
        ],
        "keywords": ["报告", "解释", "什么意思", "建议", "证据", "来源"],
    },
    {
        "intent_code": "TREND_ANALYSIS",
        "examples": [
            "看看我最近几次报告有没有变化",
            "和上次相比怎么样",
            "最近舌苔有没有变厚",
            "帮我分析一下历史趋势",
            "这几次舌象有什么变化",
            "最近一个月的报告变化",
        ],
        "keywords": ["最近", "几次", "趋势", "变化", "相比", "历史"],
    },
    {
        "intent_code": "PRIVACY_REQUEST",
        "examples": [
            "删除我的报告",
            "把这张舌头照片删掉",
            "撤回长期记忆授权",
            "不要保存我的健康信息",
            "注销我的账号",
            "查看你保存了我哪些信息",
            "删除我的历史记录",
        ],
        "keywords": ["删除", "撤回", "授权", "隐私", "注销", "保存", "历史记录"],
    },
    {
        "intent_code": "HIGH_RISK_MEDICAL",
        "examples": [
            "能不能替我判断是不是某某病",
            "帮我确诊一下是不是肾病",
            "我这个是不是糖尿病",
            "你直接告诉我我得了什么病",
        ],
        "keywords": ["确诊", "诊断", "是不是病", "得了什么病", "替代医生判断"],
    },
    {
        "intent_code": "EMERGENCY_MEDICAL",
        "examples": [
            "我现在胸痛很厉害",
            "我呼吸困难怎么办",
            "突然昏迷了怎么办",
            "大量出血怎么办",
            "严重过敏喘不上气",
            "意识不清还抽搐",
            "胸口疼得受不了",
            "喘不过气来怎么办",
        ],
        "keywords": ["胸痛", "呼吸困难", "昏迷", "大出血", "严重过敏", "意识不清", "抽搐"],
    },
]


DOMAIN_TERMS: list[dict[str, Any]] = [
    {
        "term_id": "term_dampness",
        "raw_term": "湿气重",
        "normalized_term": "痰湿相关表达",
        "term_type": "health_concept",
        "aliases": ["湿重", "湿气大", "体内湿", "身体湿", "湿气太重"],
        "related_intents": ["TONGUE_ANALYSIS_START", "HEALTH_KNOWLEDGE_QA"],
        "risk_level": "LOW",
        "enabled": True,
        "version": 1,
    },
    {
        "term_id": "term_teeth_marks",
        "raw_term": "舌头边上有牙印",
        "normalized_term": "齿痕舌",
        "term_type": "tongue_feature",
        "aliases": ["舌边有牙印", "舌头有齿痕", "牙齿印", "舌头边缘一圈印"],
        "related_intents": ["TONGUE_ANALYSIS_START", "HEALTH_KNOWLEDGE_QA"],
        "risk_level": "LOW",
        "enabled": True,
        "version": 1,
    },
    {
        "term_id": "term_greasy_coating",
        "raw_term": "舌苔黏黏的",
        "normalized_term": "腻苔",
        "term_type": "tongue_feature",
        "aliases": ["舌苔很腻", "黏黏厚厚", "舌苔油腻", "舌面发黏"],
        "related_intents": ["TONGUE_ANALYSIS_START", "HEALTH_KNOWLEDGE_QA"],
        "risk_level": "LOW",
        "enabled": True,
        "version": 1,
    },
    {
        "term_id": "term_thick_coating",
        "raw_term": "舌苔很厚",
        "normalized_term": "厚苔",
        "term_type": "tongue_feature",
        "aliases": ["厚厚一层舌苔", "舌苔厚", "舌面一层白的", "舌苔多"],
        "related_intents": ["TONGUE_ANALYSIS_START", "HEALTH_KNOWLEDGE_QA"],
        "risk_level": "LOW",
        "enabled": True,
        "version": 1,
    },
    {
        "term_id": "term_yellow_greasy",
        "raw_term": "舌苔又黄又腻",
        "normalized_term": "黄腻苔",
        "term_type": "tongue_feature",
        "aliases": ["黄黄黏黏", "黄厚腻", "舌苔发黄发腻", "黄色黏腻舌苔"],
        "related_intents": ["TONGUE_ANALYSIS_START", "HEALTH_KNOWLEDGE_QA"],
        "risk_level": "LOW",
        "enabled": True,
        "version": 1,
    },
    {
        "term_id": "term_report_delete",
        "raw_term": "删掉我的记录",
        "normalized_term": "删除报告或历史记录",
        "term_type": "privacy_action",
        "aliases": ["清空记录", "不要保存", "删掉报告", "删掉照片", "撤回授权"],
        "related_intents": ["PRIVACY_REQUEST"],
        "risk_level": "MEDIUM",
        "enabled": True,
        "version": 1,
    },
    {
        "term_id": "term_prescription",
        "raw_term": "开药",
        "normalized_term": "药物或方剂一般参考请求",
        "term_type": "health_reference",
        "aliases": ["吃什么药", "药量", "剂量", "停药", "换药", "开方子"],
        "related_intents": ["HEALTH_KNOWLEDGE_QA"],
        "risk_level": "LOW",
        "enabled": True,
        "version": 1,
    },
    {
        "term_id": "term_emergency",
        "raw_term": "急症",
        "normalized_term": "急症风险表达",
        "term_type": "medical_risk",
        "aliases": ["胸痛", "呼吸困难", "昏迷", "大出血", "严重过敏", "喘不上气"],
        "related_intents": ["EMERGENCY_MEDICAL"],
        "risk_level": "EMERGENCY",
        "enabled": True,
        "version": 1,
    },
]
